name: fire_api_dart
description: "An implementation for fire_api for dart servers using googleapis."
version: 1.5.3
repository: https://github.com/ArcaneArts/fire_api/tree/main/fire_api_dart
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  chunked_stream: ">=1.4.2"
  fire_api: ">=1.5.0"
  google_cloud: ">=0.2.0"
  googleapis: ">=13.2.0"
  googleapis_auth: ">=1.6.0"
dev_dependencies:
  lints: ^5.1.1
